name: "Sync SDK Deps"
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ETH
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-ethereum/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      - name: Sync Cosmos
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-cosmos/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      - name: Sync Algorand
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-algorand/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      - name: Sync Near
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-near/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      - name: Sync Stellar
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-stellar/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      - name: Sync Starknet
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-starknet/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      - name: Sync Solana
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-solana/dispatches \
            -d '{"event_type":"trigger-workflow"}'
