name: "Sync SDK Deps"
on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Sync ETH
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/subquery/subql-ethereum/dispatches \
            -d '{"event_type":"trigger-workflow"}'

      # - name: Trigger repo B
      #   run: |
      #     curl -X POST \
      #       -H "Authorization: token ${{ secrets.SUBQL_SDK_CI }}" \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       https://api.github.com/repos/<owner>/repo-b/dispatches \
      #       -d '{"event_type":"trigger-workflow"}'
